version: '3.8'

services:
  multi-model-medical-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8171:8000"
    volumes:
      # Mount the entire models directory
      - ./models:/app/models:ro
      # Individual model files (uncomment as needed)
      # - ./models/brain_mri_finetuned_model.h5:/app/models/brain_mri_finetuned_model.h5:ro
      # - ./models/chest_xray_model.h5:/app/models/chest_xray_model.h5:ro
      # - ./models/bone_fracture_model.h5:/app/models/bone_fracture_model.h5:ro
      # - ./models/skin_cancer_model.h5:/app/models/skin_cancer_model.h5:ro
      # - ./models/retinal_disease_model.h5:/app/models/retinal_disease_model.h5:ro
    environment:
      - PYTHONPATH=/app
      - CUDA_VISIBLE_DEVICES=0  # Set GPU if available
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s  # Increased for model loading time
    deploy:
      resources:
        limits:
          memory: 4G  # Increased memory for multiple models
        reservations:
          memory: 2G

